# Generated by Django 6.0 on 2026-02-03 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('selected_model', models.CharField(default='gpt-5-nano', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workbook',
                'verbose_name_plural': 'Workbooks',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='core.workbook')),
            ],
            options={
                'verbose_name_plural': 'Sheets',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('in_use', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.workbook')),
            ],
            options={
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('calculated_size', models.BigIntegerField()),
                ('extracted_content', models.TextField()),
                ('file', models.FileField(upload_to='backend/storage/userdata/')),
                ('is_processing', models.BooleanField(default=True)),
                ('use', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.folder')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.workbook')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conversations', models.JSONField(default=list)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Last interaction')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.workbook')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('file_processing', 'File Processing'), ('data_enrichment', 'Data Enrichment')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('cell_data', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sheet_uuid', models.UUIDField(blank=True, null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('tool_calls_used', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('source_files', models.JSONField(blank=True, default=list)),
                ('source_links', models.JSONField(blank=True, default=list)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='core.workbook')),
            ],
            options={
                'verbose_name_plural': 'Background Jobs',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('server_type', models.CharField(choices=[('http', 'HTTP API'), ('stdio', 'Stdio (subprocess)')], default='http', max_length=10)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_mcp_server_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('api_key_last4', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Credential',
                'verbose_name_plural': 'Provider Credentials',
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_provider_credential_per_user')],
            },
        ),
    ]
