# Generated by Django 6.0 on 2025-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_processing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='data',
            field=models.JSONField(default={'columns': [], 'rows': []}),
        ),
    ]
