# Generated by Django 6.0 on 2025-12-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_is_processing_alter_sheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='calculated_size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
