# Generated by Django 6.0 on 2026-01-04 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_calculated_size_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='backend/storage/userdata/'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('file_processing', 'File Processing'), ('data_enrichment', 'Data Enrichment')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('cell_data', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='core.document')),
            ],
            options={
                'verbose_name_plural': 'Background Jobs',
            },
        ),
    ]
