# Generated by Django 5.2.5 on 2026-01-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conversation_conversations_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='selected_model',
            field=models.CharField(default='gpt-5-nano', max_length=100),
        ),
    ]
