# Generated by Django 6.0 on 2026-01-11 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folder_file_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Workbook',
        ),
        migrations.AlterModelOptions(
            name='workbook',
            options={'verbose_name': 'Workbook', 'verbose_name_plural': 'Workbooks'},
        ),
        migrations.RenameField(
            model_name='backgroundjob',
            old_name='document',
            new_name='workbook',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='document',
            new_name='workbook',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='document',
            new_name='workbook',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='document',
            new_name='workbook',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='document',
            new_name='workbook',
        ),
    ]
