# Generated by Django 6.0 on 2026-01-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_document_workbook_alter_workbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='sheet_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='source_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='tool_calls_used',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
