# Generated by Django 6.0 on 2026-01-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backgroundjob_column_backgroundjob_model_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='source_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
