# Generated by Django 6.0 on 2026-01-24 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_conversation_options_mcpserver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcpserver',
            options={'ordering': ['display_name'], 'verbose_name': 'MCP Server', 'verbose_name_plural': 'MCP Servers'},
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_mcp_server_per_user'),
        ),
    ]
