# Generated by Django 6.0 on 2026-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mcpserver_options_alter_mcpserver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='server_type',
            field=models.CharField(choices=[('http', 'HTTP API'), ('stdio', 'Stdio (subprocess)')], default='http', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
