# Generated by Django 6.0 on 2026-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mcpserver_server_type_alter_mcpserver_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
